version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Appsavi0admin1
      MYSQL_DATABASE: appsavi
      MYSQL_USER: appsavi
      MYSQL_PASSWORD: Appsavi0admin1
    networks:
      web:
    ports:
      - "3306:3306"

  api:
    environment:
      - ENV=production
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://appsavi:Appsavi0admin1@db:3306/appsavi
      - JWT_SECRET_KEY=7c2a4da702389681b756dc3e19b9f9feb36ee1a4644e6ee22bf88f78bdb0d77f
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.rule=Host(`manage.weltrack.co`)"
      - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.api.middlewares=api-https-redirect"
      - "traefik.http.routers.api-secure.entrypoints=https"
      - "traefik.http.routers.api-secure.rule=Host(`manage.weltrack.co`)"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.tls.certresolver=http"
      - "traefik.http.routers.api-secure.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    security_opt:
      - no-new-privileges:true
    volumes:
      - .:/code

volumes:
  mysql_data:

networks:
  web:
    external: true
