version: "3.8"

services:
  api:
    environment:
      - DB_URL=mysql+pymysql://root:Appsavi0admin1@host.docker.internal/appsavi
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    restart: unless-stopped
    networks:
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.rule=Host(`manage.weltrack.co`)"
      - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.api.middlewares=api-https-redirect"
      - "traefik.http.routers.api-secure.entrypoints=https"
      - "traefik.http.routers.api-secure.rule=Host(`manage.weltrack.co`)"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.tls.certresolver=http"
      - "traefik.http.routers.api-secure.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    security_opt:
      - no-new-privileges:true
    volumes:
      - .:/code

networks:
  web:
    external: true
