"""create tables

Revision ID: 86c921ebf80d
Revises: 
Create Date: 2025-01-07 11:29:32.118941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c921ebf80d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_id'), 'task_status', ['id'], unique=False)
    op.create_table('zitadel_tenants',
    sa.Column('zitadel_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zitadel_tenants_id'), 'zitadel_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_zitadel_tenants_zitadel_tenant_id'), 'zitadel_tenants', ['zitadel_tenant_id'], unique=True)
    op.create_table('portal_users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['zitadel_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_users_email'), 'portal_users', ['email'], unique=True)
    op.create_index(op.f('ix_portal_users_id'), 'portal_users', ['id'], unique=False)
    op.create_table('zitadel_users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('zitadel_user_id', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('pin', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['zitadel_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zitadel_users_email'), 'zitadel_users', ['email'], unique=True)
    op.create_index(op.f('ix_zitadel_users_id'), 'zitadel_users', ['id'], unique=False)
    op.create_index(op.f('ix_zitadel_users_zitadel_user_id'), 'zitadel_users', ['zitadel_user_id'], unique=True)
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('zitadel_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zitadel_user_id'], ['zitadel_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('device_users',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('zitadel_user_id', sa.String(length=36), nullable=False),
    sa.Column('device_username', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['zitadel_user_id'], ['zitadel_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_users_id'), 'device_users', ['id'], unique=False)
    op.create_table('device_activity_logs',
    sa.Column('zitadel_user_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('device_username', sa.String(length=36), nullable=True),
    sa.Column('login_as', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device_username'], ['device_users.id'], ),
    sa.ForeignKeyConstraint(['zitadel_user_id'], ['zitadel_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_activity_logs_id'), 'device_activity_logs', ['id'], unique=False)
    op.create_table('shared_users',
    sa.Column('device_user_id', sa.String(length=36), nullable=False),
    sa.Column('shared_with_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_user_id'], ['device_users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['zitadel_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_users_id'), 'shared_users', ['id'], unique=False)
    op.create_table('portal_activity_logs',
    sa.Column('portal_user_id', sa.String(length=36), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('zitadel_user_id', sa.String(length=36), nullable=True),
    sa.Column('zitadel_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('device_user_id', sa.String(length=36), nullable=True),
    sa.Column('shared_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device_user_id'], ['device_users.id'], ),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shared_user_id'], ['shared_users.id'], ),
    sa.ForeignKeyConstraint(['zitadel_tenant_id'], ['zitadel_tenants.id'], ),
    sa.ForeignKeyConstraint(['zitadel_user_id'], ['zitadel_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_activity_logs_id'), 'portal_activity_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_activity_logs_id'), table_name='portal_activity_logs')
    op.drop_table('portal_activity_logs')
    op.drop_index(op.f('ix_shared_users_id'), table_name='shared_users')
    op.drop_table('shared_users')
    op.drop_index(op.f('ix_device_activity_logs_id'), table_name='device_activity_logs')
    op.drop_table('device_activity_logs')
    op.drop_index(op.f('ix_device_users_id'), table_name='device_users')
    op.drop_table('device_users')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_zitadel_users_zitadel_user_id'), table_name='zitadel_users')
    op.drop_index(op.f('ix_zitadel_users_id'), table_name='zitadel_users')
    op.drop_index(op.f('ix_zitadel_users_email'), table_name='zitadel_users')
    op.drop_table('zitadel_users')
    op.drop_index(op.f('ix_portal_users_id'), table_name='portal_users')
    op.drop_index(op.f('ix_portal_users_email'), table_name='portal_users')
    op.drop_table('portal_users')
    op.drop_index(op.f('ix_zitadel_tenants_zitadel_tenant_id'), table_name='zitadel_tenants')
    op.drop_index(op.f('ix_zitadel_tenants_id'), table_name='zitadel_tenants')
    op.drop_table('zitadel_tenants')
    op.drop_index(op.f('ix_task_status_id'), table_name='task_status')
    op.drop_table('task_status')
    # ### end Alembic commands ###
