"""foreign key set null on delete

Revision ID: 87f4923f4227
Revises: 86c921ebf80d
Create Date: 2025-01-08 01:11:17.739719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87f4923f4227'
down_revision: Union[str, None] = '86c921ebf80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_activity_logs_ibfk_1', 'device_activity_logs', type_='foreignkey')
    op.drop_constraint('device_activity_logs_ibfk_2', 'device_activity_logs', type_='foreignkey')
    op.drop_constraint('device_activity_logs_ibfk_3', 'device_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'device_activity_logs', 'zitadel_users', ['zitadel_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'device_activity_logs', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'device_activity_logs', 'device_users', ['device_username'], ['id'], ondelete='SET NULL')
    op.alter_column('devices', 'zitadel_user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('devices_ibfk_1', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'zitadel_users', ['zitadel_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('portal_activity_logs_ibfk_4', 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint('portal_activity_logs_ibfk_5', 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint('portal_activity_logs_ibfk_2', 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint('portal_activity_logs_ibfk_6', 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint('portal_activity_logs_ibfk_1', 'portal_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'portal_activity_logs', 'zitadel_users', ['zitadel_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'portal_activity_logs', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'portal_activity_logs', 'shared_users', ['shared_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'portal_activity_logs', 'zitadel_tenants', ['zitadel_tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'portal_activity_logs', 'device_users', ['device_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'portal_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'portal_activity_logs', type_='foreignkey')
    op.create_foreign_key('portal_activity_logs_ibfk_1', 'portal_activity_logs', 'devices', ['device_id'], ['id'])
    op.create_foreign_key('portal_activity_logs_ibfk_6', 'portal_activity_logs', 'zitadel_users', ['zitadel_user_id'], ['id'])
    op.create_foreign_key('portal_activity_logs_ibfk_2', 'portal_activity_logs', 'device_users', ['device_user_id'], ['id'])
    op.create_foreign_key('portal_activity_logs_ibfk_5', 'portal_activity_logs', 'zitadel_tenants', ['zitadel_tenant_id'], ['id'])
    op.create_foreign_key('portal_activity_logs_ibfk_4', 'portal_activity_logs', 'shared_users', ['shared_user_id'], ['id'])
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_ibfk_1', 'devices', 'zitadel_users', ['zitadel_user_id'], ['id'])
    op.alter_column('devices', 'zitadel_user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'device_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'device_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'device_activity_logs', type_='foreignkey')
    op.create_foreign_key('device_activity_logs_ibfk_3', 'device_activity_logs', 'zitadel_users', ['zitadel_user_id'], ['id'])
    op.create_foreign_key('device_activity_logs_ibfk_2', 'device_activity_logs', 'device_users', ['device_username'], ['id'])
    op.create_foreign_key('device_activity_logs_ibfk_1', 'device_activity_logs', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###
