"""log table changes

Revision ID: d1793d0cfa96
Revises: a2da679d1545
Create Date: 2024-12-31 01:16:20.461966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1793d0cfa96'
down_revision: Union[str, None] = 'a2da679d1545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_activity_logs', 'admin_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'admin_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'admin_activity_logs', 'admin_users', ['admin_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'admin_activity_logs', 'admin_users', ['admin_user_id'], ['id'])
    op.alter_column('admin_activity_logs', 'admin_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
